USERNAME = 'root'
PASSWORD = 'Passw0rd'
ADDRESS = 'localhost'
PORT = '3306'
SQLALCHEMY_DATABASE_URI = f'mysql+pymysql://{USERNAME}:{PASSWORD}@{ADDRESS}:{PORT}/port-tracker'
SECRET_KEY = "top secret"
JWT_ACCESS_LIFESPAN = {"hours": 24}
JWT_REFRESH_LIFESPAN = {"days": 30}

#TODO:
#PRAETORIAN_ROLES_DISABLED=True